"""
Phase 13 — Runtime Policy Compiler
Generates framework-agnostic runtime guardrails (OPA Rego authorization,
API gateway rate limiting) compiled from the Universal ISR's security sub-graph
and the ArchitectureGenome.

Constitutional Alignment:
- Separation of concerns: business logic (application compiler) is pure;
  security/resilience is enforced at the mesh/gateway layer.
- "Security by Design" — policies are compiled from the same SecurityPolicy
  nodes the application compiler reads, so enforcement cannot drift.
"""

from __future__ import annotations

from typing import Any, Dict, List

from constitutional_architecture.core.contracts.compiler import CompilerBackend
from constitutional_architecture.core.models.bundle import (
    ArtifactType, CompilationBundle, CompilationManifest,
)
from constitutional_architecture.core.models.genome import ArchitectureGenome
from constitutional_architecture.core.models.isr import (
    EdgeType, NodeType, UniversalISR,
)


class RuntimePolicyCompiler(CompilerBackend):
    def compile(
        self,
        isr: UniversalISR,
        genome: ArchitectureGenome,
        context: Dict[str, Any],
    ) -> CompilationBundle:
        files: Dict[str, str] = {}

        files["policies/authz.rego"] = self._generate_opa_policies(isr, genome)
        files["policies/rate_limit.yaml"] = self._generate_rate_limits(isr)

        manifest = CompilationManifest(
            artifact_type=ArtifactType.CONFIGURATION,
            domain="runtime_policy",
            files=files,
            metadata={"enforcement_points": ["opa", "envoy", "kong"]},
        )

        return CompilationBundle(
            compiler_id="runtime_policy_v1",
            target_technology="opa_envoy",
            manifests=[manifest],
        )

    def _security_model(self, isr: UniversalISR, genome: ArchitectureGenome) -> str:
        for node in isr.nodes.values():
            if node.type == NodeType.SECURITY_POLICY:
                model = node.semantic_attributes.get("model")
                if model:
                    return str(model)
        return "rbac"

    def _generate_opa_policies(self, isr: UniversalISR, genome: ArchitectureGenome) -> str:
        model = self._security_model(isr, genome)
        audit = self._auditability(isr, genome)

        lines = [
            "package authz",
            "",
            "default allow = false",
            "",
            "# Auto-generated by the Runtime Policy Compiler from ISR SecurityPolicy nodes",
            "",
        ]

        if model == "zero_trust":
            lines += [
                'allow {',
                '    input.authenticated == true',
                '    input.role == "admin"',
                '}',
                '',
                'allow {',
                '    input.authenticated == true',
                '    input.role == "user"',
                '    input.resource in input.allowed_resources',
                '}',
            ]
        elif model == "perimeter":
            lines += [
                'allow {',
                '    input.network == "internal"',
                '}',
            ]
        else:
            lines += [
                'allow {',
                '    input.role == "admin"',
                '}',
                '',
                'allow {',
                '    input.role == "user"',
                '    input.resource in input.allowed_resources',
                '}',
            ]

        if audit == "strict_compliance":
            lines += ['', 'allow {', '    input.audit_id != ""', '    input.authenticated == true', '}']

        lines += ['', 'deny[msg] {', '    not allow', '    msg := "access denied by compiled policy"', '}']

        return "\n".join(lines) + "\n"

    def _auditability(self, isr: UniversalISR, genome: ArchitectureGenome) -> str:
        for node in isr.nodes.values():
            if node.type == NodeType.OPERATIONAL_POLICY:
                level = node.semantic_attributes.get("auditability_level")
                if level:
                    return str(level)
        if genome.auditability_level is not None:
            return genome.auditability_level.value
        return "standard"

    def _generate_rate_limits(self, isr: UniversalISR) -> str:
        lines = [
            "domain: api",
            "descriptors:",
            "  - key: remote_address",
            "    rate_limit:",
            "      unit: minute",
            "      requests_per_unit: 100",
        ]

        for node in sorted(isr.nodes.values(), key=lambda n: n.id):
            if node.type != NodeType.API_ENDPOINT:
                continue
            route = str(node.semantic_attributes.get("path") or node.id)
            limit = 10 if self._is_restricted(isr, node.id) else 100
            lines += [
                "  - key: route",
                f'    value: "{route}"',
                "    rate_limit:",
                "      unit: minute",
                f"      requests_per_unit: {limit}",
            ]

        return "\n".join(lines) + "\n"

    def _is_restricted(self, isr: UniversalISR, api_id: str) -> bool:
        for edge in isr.edges:
            if edge.type == EdgeType.EXPOSES and edge.target_id == api_id:
                src = isr.nodes.get(edge.source_id)
                if src and src.semantic_attributes.get("security_classification") == "restricted":
                    return True
        return False
