"""
Phase 11 — Markdown & ADR Documentation Compiler
Generates READMEs, Mermaid ERDs, and Architectural Decision Records (ADRs).

Because it consumes the same UniversalISR, ArchitectureGenome, and IntentModel as the
code compilers, the documentation is mathematically guaranteed to be synchronized with
the generated system — stale documentation is architecturally impossible.

Constitutional Alignment:
- "Documentation should evolve alongside implementation."
- "Architectural reasoning should always remain transparent."
"""

from __future__ import annotations

import datetime
from typing import Any, Dict, List, Optional

from constitutional_architecture.compilers.documentation.base import DocumentationCompiler
from constitutional_architecture.core.models.bundle import (
    ArtifactType, CompilationBundle, CompilationManifest,
)
from constitutional_architecture.core.models.genome import (
    ApplicationArchitecture, ArchitectureGenome, PersistenceModel,
)
from constitutional_architecture.core.models.intent import IntentModel, QualityAttribute
from constitutional_architecture.core.models.isr import EdgeType, NodeType, UniversalISR


class MarkdownDocumentationCompiler(DocumentationCompiler):
    def compile(
        self,
        isr: UniversalISR,
        genome: ArchitectureGenome,
        context: Dict[str, Any],
        intent: Optional[IntentModel] = None,
    ) -> CompilationBundle:
        intent = intent or context.get("intent")

        files: Dict[str, str] = {}

        files["README.md"] = self._generate_readme(intent, genome, context)
        files["docs/domain/erd.md"] = self._generate_erd(isr)

        adr_files = self._generate_adrs(intent, genome)
        files.update(adr_files)

        files["docs/deployment/runbook.md"] = self._generate_runbook(context)

        manifest = CompilationManifest(
            artifact_type=ArtifactType.DOCUMENTATION,
            domain="docs",
            files=files,
            metadata={"format": "markdown", "diagrams": "mermaid"},
        )

        return CompilationBundle(
            compiler_id="markdown_adr",
            target_technology="markdown",
            manifests=[manifest],
        )

    def _generate_readme(
        self,
        intent: Optional[IntentModel],
        genome: ArchitectureGenome,
        context: Dict[str, Any],
    ) -> str:
        project_name = intent.project_name if intent else context.get("project_name", "Generated System")
        problem_statement = intent.problem_statement if intent else "Auto-generated by the Evolutionary Platform."
        style = genome.architecture_style or ApplicationArchitecture.MODULAR_MONOLITH
        persistence = genome.persistence_model or PersistenceModel.RELATIONAL
        security = genome.security_model or "rbac"
        deployment = genome.deployment_topology or "single_region"

        return f"""# {project_name}

## System Overview
{problem_statement}

## Architecture Profile
- **Style:** `{style.value}`
- **Persistence:** `{persistence.value}`
- **Security Model:** `{security.value}`
- **Deployment:** `{deployment.value}`

## Quick Start
Refer to the [Deployment Runbook](docs/deployment/runbook.md) for infrastructure provisioning and application deployment.

## Documentation Index
- [Domain Model & ERD](docs/domain/erd.md)
- [Architectural Decision Records](docs/architecture/adr/)
"""

    def _generate_erd(self, isr: UniversalISR) -> str:
        md = ["# Domain Entity Relationship Diagram\n", "```mermaid", "erDiagram"]

        entities = [n for n in isr.nodes.values() if n.type == NodeType.DATA_ENTITY]
        relationships = [e for e in isr.edges if e.type == EdgeType.RELATES_TO]

        for ent in entities:
            name = ent.id.replace("entity_", "").title()
            md.append(f"    {name} {{")
            md.append("        uuid id PK")
            md.append("    }")

        for rel in relationships:
            source = rel.source_id.replace("entity_", "").title()
            target = rel.target_id.replace("entity_", "").title()
            md.append(f'    {source} ||--o{{ {target} : "relates_to" }}')

        md.append("```")
        return "\n".join(md)

    def _generate_adrs(
        self,
        intent: Optional[IntentModel],
        genome: ArchitectureGenome,
    ) -> Dict[str, str]:
        files: Dict[str, str] = {}
        date_str = datetime.date.today().isoformat()

        style = genome.architecture_style or ApplicationArchitecture.MODULAR_MONOLITH

        files["docs/architecture/adr/001-architecture-style.md"] = self._create_adr(
            id="001",
            date=date_str,
            title="Architecture Style Selection",
            context=(
                f"The system requires a scalability priority of "
                f"{self._quality(intent, QualityAttribute.SCALABILITY):.2f} and "
                f"maintainability of {self._quality(intent, QualityAttribute.MAINTAINABILITY):.2f}."
            ),
            decision=f"Adopt `{style.value}` architecture.",
            alternatives=[s.value for s in ApplicationArchitecture if s != style],
            consequences=self._get_style_consequences(style),
        )

        persistence = genome.persistence_model or PersistenceModel.RELATIONAL

        files["docs/architecture/adr/002-persistence-model.md"] = self._create_adr(
            id="002",
            date=date_str,
            title="Persistence Model Selection",
            context=(
                f"Data domains require consistency models mapped from the Intent Model. "
                f"Reliability priority: "
                f"{self._quality(intent, QualityAttribute.RELIABILITY):.2f}."
            ),
            decision=f"Adopt `{persistence.value}` persistence model.",
            alternatives=[p.value for p in PersistenceModel if p != persistence],
            consequences=(
                f"Using {persistence.value} optimizes for the evolved data access "
                f"patterns but may require specialized querying capabilities."
            ),
        )

        return files

    @staticmethod
    def _quality(intent: Optional[IntentModel], attr: QualityAttribute) -> float:
        if intent is None:
            return 0.5
        return intent.quality_priorities.get(attr, 0.5)

    def _create_adr(
        self,
        id: str,
        date: str,
        title: str,
        context: str,
        decision: str,
        alternatives: List[str],
        consequences: str,
    ) -> str:
        alt_str = "\n".join([f"- {a}" for a in alternatives]) if alternatives else "- None considered"
        return f"""# ADR {id}: {title}

**Date:** {date}  
Status: Accepted (Evolved by Pareto Optimization)

## Context
{context}

## Decision
{decision}

## Alternatives Considered
{alt_str}

## Consequences & Trade-offs
{consequences}
"""

    def _get_style_consequences(self, style: ApplicationArchitecture) -> str:
        if style == ApplicationArchitecture.MICROSERVICES:
            return (
                "Increases deployment complexity and network latency (Risk), but enables "
                "independent scaling of high-load domains (Benefit), satisfying the high "
                "Scalability priority."
            )
        if style == ApplicationArchitecture.MODULAR_MONOLITH:
            return (
                "Simplifies deployment and testing (Benefit), but requires strict module "
                "boundary enforcement to prevent coupling (Risk), satisfying the high "
                "Maintainability priority."
            )
        return "Standard trade-offs apply."

    def _generate_runbook(self, context: Dict[str, Any]) -> str:
        tf_cmd = context.get("deployment_cmd", "terraform apply")
        return f"""# Deployment Runbook

## Prerequisites
- Terraform installed
- Cloud provider CLI configured

## Infrastructure Provisioning
```bash
cd infra/terraform
{tf_cmd}
```

## Database Migration
```bash
cd database/alembic
alembic upgrade head
```
"""
