from __future__ import annotations

from typing import Any, Dict, List

from constitutional_architecture.compilers.frontend.base import FrontendCompiler
from constitutional_architecture.core.models.bundle import (
    ArtifactType, CompilationBundle, CompilationManifest,
)
from constitutional_architecture.core.models.genome import ArchitectureGenome
from constitutional_architecture.core.models.isr import EdgeType, NodeType, UniversalISR


class ReactCompiler(FrontendCompiler):
    def compile(
        self,
        isr: UniversalISR,
        genome: ArchitectureGenome,
        context: Dict[str, Any],
    ) -> CompilationBundle:
        files: Dict[str, str] = {}

        files["src/types/domain.ts"] = self._generate_types(isr)
        files["src/api/client.ts"] = self._generate_api_client(isr)
        files["src/App.tsx"] = self._generate_app_shell(isr)

        component_files = self._generate_components(isr)
        files.update(component_files)

        design_tokens = context.get("design_tokens", {})
        files["tailwind.config.js"] = self._generate_design_config(design_tokens)

        source_manifest = CompilationManifest(
            artifact_type=ArtifactType.SOURCE_CODE,
            domain="frontend",
            files=files,
            metadata={"framework": "react"},
        )

        return CompilationBundle(
            compiler_id="react_vite",
            target_technology="react",
            manifests=[source_manifest],
            exposed_interfaces={"frontend_build_cmd": "npm run build", "frontend_port": 3000},
        )

    def _generate_types(self, isr: UniversalISR) -> str:
        lines = ["// Auto-generated by Evolutionary Platform - DO NOT EDIT\n"]
        for node in isr.nodes.values():
            if node.type == NodeType.DATA_ENTITY:
                name = node.id.replace("entity_", "").title()
                lines.append(f"export interface {name} {{")
                lines.append("  id: string;")
                lines.append("  // Properties derived from ISR Domain Graph")
                lines.append("}\n")
        return "\n".join(lines)

    def _generate_api_client(self, isr: UniversalISR) -> str:
        lines = [
            "// Auto-generated API Client",
            "import { AxiosInstance, AxiosResponse } from 'axios';",
            "import { apiClient } from './axiosConfig';\n",
        ]
        for node in isr.nodes.values():
            if node.type == NodeType.API_ENDPOINT:
                name = node.id.replace("api_", "").title()
                lines.append(f"export const {name}Api = {{")
                lines.append(f"  list: (): Promise<AxiosResponse<any>> => apiClient.get('/{node.id}'),")
                lines.append(f"  get: (id: string): Promise<AxiosResponse<any>> => apiClient.get(`/{node.id}/${{id}}`),")
                lines.append("};\n")
        return "\n".join(lines)

    def _generate_app_shell(self, isr: UniversalISR) -> str:
        views = [n for n in isr.nodes.values() if n.type == NodeType.FRONTEND_VIEW]
        lines = [
            "import { BrowserRouter, Routes, Route } from 'react-router-dom';",
            "// Import generated pages...",
        ]
        routes: List[str] = []
        for view in views:
            page_name = view.id.replace("fe_", "").title()
            lines.append(f"import {page_name}Page from './pages/{page_name}Page';")
            routes.append(f"        <Route path='/{page_name.lower()}' element={{<{page_name}Page />}} />")
        lines.extend([
            "\nexport const App = () => (",
            "  <BrowserRouter>",
            "    <Routes>",
            *routes,
            "    </Routes>",
            "  </BrowserRouter>",
            ");",
        ])
        return "\n".join(lines)

    def _generate_components(self, isr: UniversalISR) -> Dict[str, str]:
        files: Dict[str, str] = {}
        capabilities = [
            n for n in isr.nodes.values()
            if n.type in (NodeType.SERVICE, NodeType.COMPONENT)
        ]
        for cap in capabilities:
            page_name = cap.id.replace("svc_", "").replace("comp_", "").title()
            policy = self._get_security_policy(isr, cap.id)
            tsx = "\n".join([
                f"import {{ {page_name}Api }} from '../api/client';",
                f"// Security Policy: {policy}",
                f"export const {page_name}Page = () => {{",
                f"  // TODO: Implement UI using Design System Tokens",
                f"  return <div>{page_name} Management Dashboard</div>;",
                f"}};",
            ])
            files[f"src/pages/{page_name}Page.tsx"] = tsx
        return files

    def _get_security_policy(self, isr: UniversalISR, target_id: str) -> str:
        for edge in isr.edges:
            if edge.target_id == target_id and edge.type == EdgeType.SECURES:
                policy = isr.nodes.get(edge.source_id)
                if policy:
                    return policy.semantic_attributes.get("model", "unknown")
        return "none"

    def _generate_design_config(self, tokens: Dict[str, Any]) -> str:
        return "// Tailwind config injected from Frontend Design Genome\nmodule.exports = {};"
