"""
FastAPI foundation compiler backend.

Compiles ISR into a deployable FastAPI service foundation.
"""

from __future__ import annotations

from typing import Any

from ...models import (
    BackendCapabilities,
    BackendManifest,
    CompilationContext,
    CompilationOutput,
    ValidationReport,
)
from ...sdk.artifacts import CompilationOutputBuilder
from ...sdk.base import CompilerBackendBase
from .isr_helpers import (
    infer_http_method,
    iter_data_models,
    iter_services,
    normalize_api,
    normalize_data_model,
    project_name,
    project_slug,
    python_identifier,
    pascal_case,
    python_type,
)


REQUIREMENTS = """fastapi>=0.111
uvicorn>=0.30
pydantic>=2.7
"""

DEV_REQUIREMENTS = """pytest>=8.0
httpx>=0.27
"""

DOCKERFILE = """FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

HEALTH_PY = """from fastapi import APIRouter

router = APIRouter(tags=["health"])


@router.get("/health/live")
def health_live():
    return {"status": "live"}


@router.get("/health/ready")
def health_ready():
    return {"status": "ready"}
"""

TEST_PY = """from fastapi.testclient import TestClient

from app.main import app


client = TestClient(app)


def test_health_live():
    response = client.get("/health/live")
    assert response.status_code == 200
    assert response.json() == {"status": "live"}


def test_openapi_available():
    response = client.get("/openapi.json")
    assert response.status_code == 200
"""


class FastAPIFoundationBackend(CompilerBackendBase):
    """Compiles ISR into a FastAPI service foundation."""

    def __init__(self) -> None:
        self.manifest = BackendManifest(
            backend_id="python.fastapi.foundation",
            name="FastAPI Foundation Backend",
            version="0.1.0",
            description=(
                "Compiles ISR into a deployable FastAPI service foundation."
            ),
            capabilities=BackendCapabilities(
                supported_targets=["service"],
                languages=["Python"],
                frameworks=["FastAPI"],
                artifact_types=[
                    "source_code",
                    "configuration",
                    "tests",
                    "dockerfile",
                ],
                deployment_targets=["docker"],
                maturity="production",
            ),
            entrypoint=(
                "compiler.backends.production.fastapi_backend:"
                "FastAPIFoundationBackend"
            ),
        )
        self.config = {}

    def validate_configuration(self, config: dict[str, Any]) -> ValidationReport:
        """Default configuration validation — accepts any config."""
        return ValidationReport(valid=True, issues=[])

    def compile(self, context: CompilationContext) -> CompilationOutput:
        isr = context.isr

        builder = CompilationOutputBuilder()

        data_models = list(iter_data_models(isr))
        services = list(iter_services(isr))

        models_py = self._generate_models_py(data_models)
        repositories_py = self._generate_repositories_py(data_models)
        routes_py = self._generate_routes_py(isr, data_models, services)

        main_py = self._generate_main_py(isr)

        builder.add_artifact("app/__init__.py", "", "text/plain")
        builder.add_artifact("app/main.py", main_py, "text/x-python")
        builder.add_artifact("app/health.py", HEALTH_PY, "text/x-python")
        builder.add_artifact("app/models.py", models_py, "text/x-python")
        builder.add_artifact(
            "app/repositories.py",
            repositories_py,
            "text/x-python",
        )
        builder.add_artifact("app/routes.py", routes_py, "text/x-python")

        builder.add_artifact("tests/__init__.py", "", "text/plain")
        builder.add_artifact("tests/test_app.py", TEST_PY, "text/x-python")

        builder.add_artifact("requirements.txt", REQUIREMENTS, "text/plain")
        builder.add_artifact(
            "dev-requirements.txt",
            DEV_REQUIREMENTS,
            "text/plain",
        )
        builder.add_artifact("Dockerfile", DOCKERFILE, "text/plain")

        builder.add_markdown_artifact(
            "README.md",
            "\n".join(
                [
                    f"# {project_name(isr)}",
                    "",
                    "Generated by the FastAPI foundation compiler backend.",
                    "",
                    "## Run",
                    "",
                    "```bash",
                    "pip install -r requirements.txt",
                    "uvicorn app.main:app --reload",
                    "```",
                    "",
                    "## Test",
                    "",
                    "```bash",
                    "pip install -r dev-requirements.txt",
                    "pytest -q",
                    "```",
                    "",
                ]
            ),
        )

        builder.add_log("Compiled FastAPI foundation backend artifacts.")

        return builder.build()

    def _generate_models_py(self, data_models) -> str:
        lines = [
            "from __future__ import annotations",
            "",
            "from datetime import datetime",
            "from typing import Any, Dict, List, Optional",
            "",
            "from pydantic import BaseModel",
            "",
        ]

        seen_classes: set[str] = set()

        for raw_model in data_models:
            model = normalize_data_model(raw_model)
            class_name = pascal_case(model["name"]) or "GeneratedModel"

            if class_name in seen_classes:
                continue

            seen_classes.add(class_name)

            lines.append(f"class {class_name}(BaseModel):")
            lines.append("    id: Optional[str] = None")
            lines.append("    created_at: Optional[datetime] = None")

            fields = model.get("fields", {}) or {}

            if not fields:
                lines.append("    value: Optional[str] = None")

            for field_name, field_type in fields.items():
                field_slug = python_identifier(field_name)

                if not field_slug or field_slug in {"id", "created_at"}:
                    continue

                type_hint = python_type(field_type)

                lines.append(
                    f"    {field_slug}: Optional[{type_hint}] = None"
                )

            lines.append("")

        if not seen_classes:
            lines.append("class GeneratedModel(BaseModel):")
            lines.append("    id: Optional[str] = None")
            lines.append("    created_at: Optional[datetime] = None")
            lines.append("    value: Optional[str] = None")
            lines.append("")

        return "\n".join(lines)

    def _generate_repositories_py(self, data_models) -> str:
        lines = [
            "from __future__ import annotations",
            "",
            "import uuid",
            "from datetime import datetime, timezone",
            "from typing import Any, Dict",
            "",
            "",
            "class InMemoryRepository:",
            "    def __init__(self) -> None:",
            "        self._items: Dict[str, Dict[str, Any]] = {}",
            "",
            "    def list(self):",
            "        return sorted(",
            "            self._items.values(),",
            "            key=lambda item: item.get('created_at', ''),",
            "        )",
            "",
            "    def get(self, item_id: str):",
            "        return self._items.get(item_id)",
            "",
            "    def create(self, payload: Dict[str, Any]):",
            "        item_id = payload.get('id') or str(uuid.uuid4())",
            "        now = datetime.now(timezone.utc).isoformat()",
            "",
            "        payload['id'] = item_id",
            "        payload.setdefault('created_at', now)",
            "",
            "        self._items[item_id] = payload",
            "        return payload",
            "",
            "    def update(self, item_id: str, payload: Dict[str, Any]):",
            "        item = self._items.get(item_id)",
            "",
            "        if item is None:",
            "            return None",
            "",
            "        item.update(payload)",
            "        self._items[item_id] = item",
            "        return item",
            "",
            "    def delete(self, item_id: str) -> bool:",
            "        return self._items.pop(item_id, None) is not None",
            "",
            "",
            "repositories = {",
        ]

        seen_slugs: set[str] = set()

        for raw_model in data_models:
            model = normalize_data_model(raw_model)
            slug = python_identifier(model["name"])

            if not slug or slug in seen_slugs:
                continue

            seen_slugs.add(slug)

            lines.append(f'    "{slug}": InMemoryRepository(),')

        lines.append("}")
        lines.append("")

        return "\n".join(lines)

    def _generate_routes_py(self, isr, data_models, services) -> str:
        model_class_names: list[str] = []
        model_slugs: list[str] = []

        for raw_model in data_models:
            model = normalize_data_model(raw_model)
            class_name = pascal_case(model["name"]) or "GeneratedModel"
            slug = python_identifier(model["name"])

            if not slug or slug in model_slugs:
                continue

            model_slugs.append(slug)
            model_class_names.append(class_name)

        lines = [
            "from __future__ import annotations",
            "",
            "from typing import List",
            "",
            "from fastapi import APIRouter, HTTPException",
        ]

        if model_class_names:
            lines.append(
                "from .models import "
                + ", ".join(sorted(set(model_class_names)))
            )

        lines.append("from .repositories import repositories")
        lines.append("")
        lines.append("router = APIRouter()")
        lines.append("")

        # Operation routes.
        lines.append('operations_router = APIRouter(tags=["operations"])')
        lines.append("")

        used_functions: set[str] = set()

        for service in services:
            service_name = service.get("name", "Service")
            service_slug = python_identifier(service_name)

            if not service_slug:
                continue

            apis = service.get("apis", []) or []

            for raw_api in apis:
                api = normalize_api(raw_api)
                api_name = api.get("name", "operation")
                api_slug = python_identifier(api_name)

                if not api_slug:
                    continue

                method = infer_http_method(api_name).lower()

                func_name = f"op_{service_slug}_{api_slug}"

                if func_name in used_functions:
                    func_name = f"{func_name}_{len(used_functions)}"

                used_functions.add(func_name)

                lines.append(
                    f'@operations_router.{method}('
                    f'"/operations/{service_slug}/{api_slug}", '
                    f'tags=["operations"])'
                )
                lines.append(f"def {func_name}() -> dict:")
                lines.append(
                    "    return {"
                    f"'operation': '{api_name}', "
                    f"'service': '{service_name}', "
                    "'status': 'accepted'}"
                )
                lines.append("")

        lines.append("router.include_router(operations_router)")
        lines.append("")

        # Model CRUD routes.
        for slug, class_name in zip(model_slugs, model_class_names):
            router_name = f"model_router_{slug}"

            lines.append(
                f'{router_name} = APIRouter('
                f'prefix="/models/{slug}", tags=["{slug}"])'
            )
            lines.append("")

            lines.append(
                f'@{router_name}.get("", response_model=List[{class_name}])'
            )
            lines.append(f"def list_{slug}() -> List[{class_name}]:")
            lines.append(
                f"    return [{class_name}(**item) "
                f'for item in repositories["{slug}"].list()]'
            )
            lines.append("")

            lines.append(
                f'@{router_name}.post("", response_model={class_name}, '
                "status_code=201)"
            )
            lines.append(f"def create_{slug}(payload: {class_name}):")
            lines.append(
                f"    return {class_name}("
                f'repositories["{slug}"].create(payload.model_dump()))'
            )
            lines.append("")

            lines.append(
                f'@{router_name}.get("/{{item_id}}", '
                f"response_model={class_name})"
            )
            lines.append(f"def get_{slug}(item_id: str):")
            lines.append(
                f'    item = repositories["{slug}"].get(item_id)'
            )
            lines.append("    if item is None:")
            lines.append(
                '        raise HTTPException('
                'status_code=404, detail="Item not found")'
            )
            lines.append(f"    return {class_name}(**item)")
            lines.append("")

            lines.append(
                f'@{router_name}.put("/{{item_id}}", '
                f"response_model={class_name})"
            )
            lines.append(
                f"def update_{slug}(item_id: str, payload: {class_name}):"
            )
            lines.append(
                f'    item = repositories["{slug}"].update('
                "item_id, payload.model_dump(exclude_unset=True))"
            )
            lines.append("    if item is None:")
            lines.append(
                '        raise HTTPException('
                'status_code=404, detail="Item not found")'
            )
            lines.append(f"    return {class_name}(**item)")
            lines.append("")

            lines.append(
                f'@{router_name}.delete("/{{item_id}}", status_code=204)'
            )
            lines.append(f"def delete_{slug}(item_id: str):")
            lines.append(
                f'    deleted = repositories["{slug}"].delete(item_id)'
            )
            lines.append("    if not deleted:")
            lines.append(
                '        raise HTTPException('
                'status_code=404, detail="Item not found")'
            )
            lines.append("    return None")
            lines.append("")

            lines.append(f"router.include_router({router_name})")
            lines.append("")

        return "\n".join(lines)

    def _generate_main_py(self, isr) -> str:
        title = project_name(isr)
        version = str(isr.get("version", "0.1.0"))

        return "\n".join(
            [
                "from fastapi import FastAPI",
                "",
                "from .health import router as health_router",
                "from .routes import router as generated_router",
                "",
                f'app = FastAPI(title="{title}", version="{version}")',
                "",
                "app.include_router(health_router)",
                "app.include_router(generated_router)",
                "",
            ]
        )