"""
PostgreSQL schema compiler backend.

Compiles ISR data models into PostgreSQL DDL.
"""

from __future__ import annotations

from ...models import (
    BackendCapabilities,
    BackendManifest,
    CompilationContext,
    CompilationOutput,
)
from ...sdk.artifacts import CompilationOutputBuilder
from ...sdk.base import CompilerBackendBase
from .isr_helpers import (
    iter_data_models,
    normalize_data_model,
    project_name,
    python_identifier,
    sql_type,
)


class PostgresSchemaBackend(CompilerBackendBase):
    """Compiles ISR data models into PostgreSQL schema artifacts."""

    def __init__(self) -> None:
        self.manifest = BackendManifest(
            backend_id="postgres.schema",
            name="PostgreSQL Schema Backend",
            version="0.1.0",
            description="Compiles ISR data models into PostgreSQL DDL.",
            capabilities=BackendCapabilities(
                supported_targets=["database"],
                languages=["SQL"],
                frameworks=["PostgreSQL"],
                artifact_types=["sql", "migration", "markdown"],
                deployment_targets=["database"],
                maturity="production",
            ),
            entrypoint=(
                "compiler.backends.production.postgres_backend:"
                "PostgresSchemaBackend"
            ),
        )
        self.config = {}

    def compile(self, context: CompilationContext) -> CompilationOutput:
        isr = context.isr

        builder = CompilationOutputBuilder()

        sql_lines = [
            "-- Generated by postgres.schema backend",
            "-- The ISR remains the architectural source of truth.",
            "",
        ]

        markdown_lines = [
            "# PostgreSQL Schema",
            "",
            f"Project: {project_name(isr)}",
            "",
            "## Tables",
            "",
        ]

        seen_tables: set[str] = set()

        for raw_model in iter_data_models(isr):
            model = normalize_data_model(raw_model)
            table_name = python_identifier(model["name"])

            if not table_name or table_name in seen_tables:
                continue

            seen_tables.add(table_name)

            columns = [
                "    id TEXT PRIMARY KEY",
                "    created_at TIMESTAMPTZ NOT NULL DEFAULT now()",
            ]

            fields = model.get("fields", {}) or {}

            for field_name, field_type in fields.items():
                column_name = python_identifier(field_name)

                if not column_name or column_name in {"id", "created_at"}:
                    continue

                columns.append(
                    f"    {column_name} {sql_type(field_type)}"
                )

            sql_lines.append(f"CREATE TABLE IF NOT EXISTS {table_name} (")
            sql_lines.append(",\n".join(columns))
            sql_lines.append(");")
            sql_lines.append("")

            markdown_lines.append(f"- `{table_name}`")

        builder.add_artifact(
            path="migrations/0001_initial.sql",
            content="\n".join(sql_lines),
            content_type="text/plain",
        )

        builder.add_markdown_artifact(
            path="docs/postgres-schema.md",
            content="\n".join(markdown_lines),
        )

        builder.add_log("Compiled PostgreSQL schema from ISR data models.")

        return builder.build()