from __future__ import annotations

import time
from typing import Any

from constitutional_architecture.compiler.backends.backend_selector import BackendSelector
from constitutional_architecture.compiler.compiler_context import CompilerContext
from constitutional_architecture.compiler.pass_interface import CompilerPass, PassResult


class CodeGenerationPass(CompilerPass):
    @property
    def identifier(self) -> str:
        return "code_generation"

    @property
    def description(self) -> str:
        return "Generate implementation artifacts via compiler backends"

    @property
    def dependencies(self) -> list[str]:
        return ["lowering"]

    @property
    def input_requirements(self) -> set[str]:
        return {"bir_available"}

    @property
    def output_guarantees(self) -> set[str]:
        return {"artifacts_generated"}

    def execute(self, ctx: CompilerContext) -> PassResult:
        start = time.perf_counter()

        if ctx.bir is None:
            ctx.diagnostics.error("COMP-CODE-001", "BIR not available; cannot generate code")
            return PassResult(success=False, description="BIR not available")

        if ctx.backend_registry is None:
            ctx.diagnostics.error("COMP-CODE-002", "Backend registry not configured")
            return PassResult(success=False, description="Backend registry not configured")

        selector = BackendSelector(ctx.backend_registry)
        backends = selector.select(ctx.config)

        if not backends:
            ctx.diagnostics.warning("COMP-CODE-003", f"No registered backends match targets: {ctx.config.target_backends}")
            return PassResult(success=False, description="No backends selected")

        missing = selector.validate_selection(ctx.config)
        for name in missing:
            ctx.diagnostics.warning("COMP-CODE-004", f"Requested backend '{name}' is not registered")

        total_artifacts = 0
        backend_metrics: dict[str, dict[str, Any]] = {}

        for backend in backends:
            backend_start = time.perf_counter()
            try:
                validation_diags = backend.validate(ctx.bir)
                for diag in validation_diags:
                    ctx.diagnostics.add(diag)

                bindings = backend.bind_capabilities(ctx.capability_contracts)
                result = backend.compile(ctx.bir, bindings)

                for artifact in result.artifacts:
                    ctx.artifacts.append(artifact)
                    total_artifacts += 1
                    if hasattr(artifact, "source_mapping") and artifact.source_mapping:
                        ctx.add_source_mapping({
                            "artifact_path": artifact.path,
                            "backend": backend.name,
                            "isr_node_id": artifact.source_mapping.isr_node_id,
                            "bir_node_id": getattr(artifact.source_mapping, "bir_node_id", ""),
                        })

                for diag in result.diagnostics:
                    ctx.diagnostics.add(diag)

                unsupported = backend.report_unsupported(ctx.bir)
                for feature in unsupported:
                    ctx.diagnostics.warning("COMP-CODE-005", f"Backend '{backend.name}' does not support: {feature}")

                backend_duration = (time.perf_counter() - backend_start) * 1000
                backend_metrics[backend.name] = {
                    "artifacts": len(result.artifacts),
                    "duration_ms": backend_duration,
                    "bindings": len(bindings),
                    "unsupported": len(unsupported),
                }

            except Exception as e:
                ctx.diagnostics.error("COMP-CODE-006", f"Backend '{backend.name}' failed: {e}")
                backend_metrics[backend.name] = {"error": str(e)}

        duration = (time.perf_counter() - start) * 1000

        if total_artifacts == 0:
            ctx.diagnostics.error("COMP-CODE-007", "No artifacts generated by any backend")
            return PassResult(success=False, description="No artifacts generated", metrics=backend_metrics)

        ctx.diagnostics.info("COMP-CODE-008", f"Generated {total_artifacts} artifact(s) from {len(backends)} backend(s)")

        return PassResult(
            success=True,
            description=f"Generated {total_artifacts} artifacts",
            metrics={"total_artifacts": total_artifacts, "backends_used": len(backends),
                     "backend_metrics": backend_metrics, "duration_ms": duration},
        )
