"""
Phase 10 — PostgreSQL Database Compiler
Generates DDL, RLS (for multi-tenancy), and Alembic migrations directly from the ISR
Data Domain Graph — independent of any ORM.

Constitutional Alignment:
- "Prefer Domain-Driven Design... Explicit interfaces, Strong module boundaries."
- "Security is a core architectural concern. Never treat security as an afterthought."
"""

from __future__ import annotations

from typing import Any, Dict, List

from constitutional_architecture.compilers.database.base import DatabaseCompiler
from constitutional_architecture.core.models.bundle import (
    ArtifactType, CompilationBundle, CompilationManifest,
)
from constitutional_architecture.core.models.genome import (
    ArchitectureGenome, TenancyStrategy,
)
from constitutional_architecture.core.models.isr import EdgeType, NodeType, UniversalISR


class PostgresCompiler(DatabaseCompiler):
    def compile(
        self,
        isr: UniversalISR,
        genome: ArchitectureGenome,
        context: Dict[str, Any],
    ) -> CompilationBundle:
        files: Dict[str, str] = {}

        entities = self._extract_entities(isr)

        files["schema.sql"] = self._generate_ddl(entities, genome)

        tenancy = genome.tenancy_strategy
        if tenancy in (
            TenancyStrategy.MULTI_TENANT_SHARED,
            TenancyStrategy.MULTI_TENANT_ISOLATED,
        ):
            files["rls_policies.sql"] = self._generate_rls(entities)

        files["alembic/versions/001_initial_schema.py"] = self._generate_alembic_migration(
            entities, genome,
        )

        manifest = CompilationManifest(
            artifact_type=ArtifactType.DATABASE_MIGRATION,
            domain="database",
            files=files,
            metadata={"engine": "postgresql", "migration_tool": "alembic"},
        )

        return CompilationBundle(
            compiler_id="postgres_alembic",
            target_technology="postgresql",
            manifests=[manifest],
            exposed_interfaces={"db_connection_string_env": "DATABASE_URL"},
        )

    def _extract_entities(self, isr: UniversalISR) -> List[Dict[str, Any]]:
        entities: List[Dict[str, Any]] = []
        for node_id, node in isr.nodes.items():
            if node.type != NodeType.DATA_ENTITY:
                continue
            entity = {
                "id": node_id,
                "name": node_id.replace("entity_", ""),
                "attributes": [],
                "fks": [],
                "policies": [],
            }
            for edge in isr.edges:
                if edge.source_id == node_id and edge.type == EdgeType.HAS_ATTRIBUTE:
                    attr_node = isr.nodes.get(edge.target_id)
                    if attr_node:
                        entity["attributes"].append(attr_node.semantic_attributes)
                elif edge.source_id == node_id and edge.type == EdgeType.RELATES_TO:
                    target = isr.nodes.get(edge.target_id)
                    if target:
                        entity["fks"].append(target.id.replace("entity_", ""))
                elif edge.source_id == node_id and edge.type == EdgeType.GOVERNED_BY:
                    policy_node = isr.nodes.get(edge.target_id)
                    if policy_node:
                        entity["policies"].append(policy_node.type.value)
            entities.append(entity)
        return entities

    def _generate_ddl(self, entities: List[Dict], genome: ArchitectureGenome) -> str:
        ddl = ["-- Auto-generated by Evolutionary Platform Database Compiler\n"]

        tenancy = genome.tenancy_strategy
        multi_tenant = tenancy == TenancyStrategy.MULTI_TENANT_SHARED

        for ent in entities:
            table_name = ent["name"]
            ddl.append(f"CREATE TABLE {table_name} (")
            ddl.append("    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")

            if multi_tenant:
                ddl.append("    tenant_id UUID NOT NULL,")

            for attr in ent["attributes"]:
                col_name = attr.get("name", "unknown")
                col_type = attr.get("sql_type", "TEXT")
                nullable = "NULL" if attr.get("optional", False) else "NOT NULL"
                ddl.append(f"    {col_name} {col_type} {nullable},")

            for fk in ent["fks"]:
                ddl.append(f"    {fk}_id UUID REFERENCES {fk}(id),")

            ddl.append("    created_at TIMESTAMPTZ DEFAULT NOW()")
            ddl.append(");\n")

        return "\n".join(ddl)

    def _generate_rls(self, entities: List[Dict]) -> str:
        rls = ["-- Row-Level Security Policies for Multi-Tenancy\n"]

        for ent in entities:
            table_name = ent["name"]
            rls.append(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY;")
            rls.append(f"""
CREATE POLICY tenant_isolation_policy ON {table_name}
    USING (tenant_id = current_setting('app.current_tenant_id')::UUID);
""")
        return "\n".join(rls)

    def _generate_alembic_migration(
        self,
        entities: List[Dict],
        genome: ArchitectureGenome,
    ) -> str:
        return '''"""Initial schema generation from ISR
Revision ID: 001
Revises:
"""
from alembic import op
import sqlalchemy as sa


def upgrade():
    # The op.execute() will run the compiled DDL and RLS scripts
    with open('schema.sql', 'r') as f:
        op.execute(f.read())

    with open('rls_policies.sql', 'r') as f:
        op.execute(f.read())


def downgrade():
    # Drop tables in reverse dependency order
    pass
'''
