"""R2 -- Evolution Engine application package.

Technology-neutral evolution primitives: failure classification (R2.1/R2.2),
the candidate sandbox, mutation operators, and the causal ledger (R2.6).
"""
from tiannara.application.evolution.candidate_sandbox import (
    CandidateSandbox,
    CompiledCandidate,
    RunResult,
    attempt_repair_cycle,
)
from tiannara.application.evolution.candidate_gate import (
    BrokenTreeIntactInvariant,
    CandidateGate,
    CandidateVerdict,
    Gate,
    GateContext,
    GateResult,
    PerformanceGate,
    ProtectedInvariant,
    SecurityGate,
)
from tiannara.application.evolution.ledger import (
    EvolutionLedger,
    EvolutionEvent,
    EvolutionRecord,
    EventType,
    SelectionRecord,
    project_record,
    project_selection,
    stable_isr_hash,
)
from tiannara.application.evolution.transition_restoration import (
    RepairedCandidate,
    TransitionRestoration,
    apply_restoration,
)
from tiannara.application.evolution.compiler_sandbox import (
    RealBackendSandbox,
    docker_available,
    hash_artifact,
    hash_run,
)
from tiannara.application.evolution.fitness import (
    FitnessVector,
    ScoredCandidate,
    compute_fitness,
)
from tiannara.application.evolution.mutation_operators import (
    EMPTY_DELTA,
    ISRDelta,
    MutationCandidate,
    MutationOperator,
    NullMutation,
    TransitionRestorationOperator,
)
from tiannara.application.evolution.competitive_evolution import (
    CompetitiveEvolutionCoordinator,
    DeterministicComplexityPreference,
    EliteAdvancementStrategy,
    SelectionDecision,
    SelectionStrategy,
    pareto_frontier,
    score_candidate,
)
from tiannara.application.evolution.variation import (
    ActionInjectionOperator,
    AwaitingSurfaceIntactInvariant,
    ConstructiveVariationOperator,
    CrossoverOperator,
    FSMRepairVariation,
    GuardRelaxationOperator,
    NullCrossover,
    RandomFSMExploration,
    TestDeletionMutation,
)
from tiannara.application.evolution.autonomous_repair import (
    AutonomousRepairCoordinator,
    AutonomousRepairResult,
)
from tiannara.application.evolution.evolution_state import (
    DiversityMetrics,
    EvolutionState,
    GenerationState,
    PopulationSnapshot,
    TerminationReason,
    derive_evolution_id,
    derive_generation_id,
)
from tiannara.application.evolution.diversity import DiversityObserver
from tiannara.application.evolution.anti_monoculture import (
    DeterministicDiversityInjection,
    DiversityDiagnostics,
    DiversityPreservationPolicy,
    MonocultureDetector,
    MonocultureDiagnostic,
    MonocultureThresholds,
)
from tiannara.application.evolution.multi_generation_evolution import (
    MultiGenerationEvolutionCoordinator,
)
from tiannara.application.evolution.operator_scheduling import (
    BudgetAllocation,
    EvidenceBasedScheduler,
    OperatorScheduler,
    OperatorStatistics,
)
from tiannara.application.evolution.multi_defect import (
    CumulativeResolutionTracker,
    DefectResolutionProfile,
    DefectSet,
    MultiDefectEvaluator,
    MultiDefectGeneration,
    MultiDefectRunResult,
    MultiDefectScore,
    MultiDefectSelector,
    MultiDefectVariation,
    ObservationBoundarySandbox,
)
from tiannara.application.evolution.identity import (
    CanonicalizationError,
    FSMSemanticProjector,
    ISRIdentity,
    IdentityExtractor,
    ProvenanceIdentity,
    RuntimeTagged,
    SemanticProjector,
    canonicalize,
    semantic_equivalent,
    tag_runtime,
)
from tiannara.application.evolution.reproducibility_audit import (
    CrossRunReport,
    IdentitySeparationReport,
    ReproducibilityAuditor,
)
from tiannara.application.evolution.evolution_certification import (
    CertificationStatus,
    DimensionResult,
    DimensionVerifier,
    EngineVerdict,
    EvolutionCertificationArtifact,
    EvolutionCertifier,
)
from tiannara.application.evolution.evolution_certification_dimensions import (
    BEHAVIORAL_DIMENSIONS,
    CertificationHarness,
    DEBT_DIMENSIONS,
    build_all_dimension_verifiers,
    build_debt_dimension_verifiers,
    build_dimension_verifiers,
)

__all__ = [
    "CandidateSandbox",
    "CandidateGate",
    "CandidateVerdict",
    "CompiledCandidate",
    "BrokenTreeIntactInvariant",
    "EvolutionLedger",
    "EvolutionEvent",
    "EvolutionRecord",
    "EventType",
    "FitnessVector",
    "Gate",
    "GateContext",
    "GateResult",
    "PerformanceGate",
    "ProtectedInvariant",
    "SecurityGate",
    "RealBackendSandbox",
    "RepairedCandidate",
    "RunResult",
    "SelectionRecord",
    "TransitionRestoration",
    "TransitionRestorationOperator",
    "apply_restoration",
    "attempt_repair_cycle",
    "compute_fitness",
    "docker_available",
    "hash_artifact",
    "hash_run",
    "stable_isr_hash",
    "CompetitiveEvolutionCoordinator",
    "DeterministicComplexityPreference",
    "EliteAdvancementStrategy",
    "EMPTY_DELTA",
    "EvolutionEvent",
    "EventType",
    "MutationCandidate",
    "MutationOperator",
    "ISRDelta",
    "NullMutation",
    "SelectionDecision",
    "SelectionStrategy",
    "pareto_frontier",
    "score_candidate",
    "ActionInjectionOperator",
    "AwaitingSurfaceIntactInvariant",
    "ConstructiveVariationOperator",
    "CrossoverOperator",
    "FSMRepairVariation",
    "GuardRelaxationOperator",
    "NullCrossover",
    "RandomFSMExploration",
    "TestDeletionMutation",
    "AutonomousRepairCoordinator",
    "AutonomousRepairResult",
    "DiversityMetrics",
    "DiversityObserver",
    "DeterministicDiversityInjection",
    "DiversityDiagnostics",
    "DiversityPreservationPolicy",
    "MonocultureDetector",
    "MonocultureDiagnostic",
    "MonocultureThresholds",
    "EvolutionState",
    "GenerationState",
    "PopulationSnapshot",
    "TerminationReason",
    "MultiGenerationEvolutionCoordinator",
    "BudgetAllocation",
    "EvidenceBasedScheduler",
    "OperatorScheduler",
    "OperatorStatistics",
    "derive_evolution_id",
    "derive_generation_id",
    "CumulativeResolutionTracker",
    "DefectResolutionProfile",
    "DefectSet",
    "MultiDefectEvaluator",
    "MultiDefectGeneration",
    "MultiDefectRunResult",
    "MultiDefectScore",
    "MultiDefectSelector",
    "MultiDefectVariation",
    "ObservationBoundarySandbox",
    "CanonicalizationError",
    "FSMSemanticProjector",
    "ISRIdentity",
    "IdentityExtractor",
    "ProvenanceIdentity",
    "RuntimeTagged",
    "SemanticProjector",
    "canonicalize",
    "semantic_equivalent",
    "tag_runtime",
    "CrossRunReport",
    "IdentitySeparationReport",
    "ReproducibilityAuditor",
    "CertificationStatus",
    "DimensionResult",
    "DimensionVerifier",
    "EngineVerdict",
    "EvolutionCertificationArtifact",
    "EvolutionCertifier",
    "BEHAVIORAL_DIMENSIONS",
    "CertificationHarness",
    "DEBT_DIMENSIONS",
    "build_all_dimension_verifiers",
    "build_debt_dimension_verifiers",
    "build_dimension_verifiers",
]
